baseURL = "https://www.joshkasuboski.com/"
title = "Josh Kasuboski"
copyright = "Copyright © 2020, Josh Kasuboski"
languageCode = "en-US"
theme = "kasublogski"
paginate = 5
enableEmoji = true

[params]
  Author = "Josh Kasuboski"
  Description = "Josh Kasuboski's personal site"
  Subtitle = ""
  Avatar = "img/josh-scotland.jpg"
  Biography = "Josh Kasuboski is currently interested in developer productivity. He works to make it easier for a developer to take code from laptop to production."
  ShowBio = true
  PermalinkText = "🔗"

  # Contact/social-network identifiers for social icons
  EmailAddress = "josh.kasuboski@gmail.com"
  # FacebookUser = "FacebookUserName"
  # FlickrUser = "FlickrUserName"
  GitHubUser = "kasuboski"
  # GitLabUser = "GitLabUserName"
  # GlitchUser = "GlitchUserName"
  # KeybaseUser = "KeybaseUserName"
  LinkedInUser = "joshkasuboski"
  # MediumUser = "MediumUserName"
  # MicroBlogUser = "MicroBlogUserName"
  # RedditUser = "RedditUserName"
  # StackOverflowUser = "StackOverflowUserName"
  # TumblrUser = "TumblrUserName"
  # TwitterUser = "TwitterUserName"

  # These are parameters used for indieweb identity. You should set these along
  # with the above email/social network parameters.
  [params.indieWeb]
    EmailAddress = "josh.kasuboski@gmail.com"
    # FlickrUser = "FlickrUserName"
    GitHubUser = "kasuboski"
    # TwitterUser = "TwitterUserName"
    # MicroBlogUser = "MicroBlogUserName"
    Country = "United States"
    City = "Austin"

  [params.endpoints]
    Microsub = "https://microsub.joshcorp.co/microsub"
