name: github pages

on:
  push:
    paths-ignore:
    - 'README.md'

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.62.2'

    - name: Build
      run: hugo --minify

    - uses: actions/cache@v2
      with:
        path: tmp/.htmltest
        key: ${{ runner.os }}-htmltest

    - name: HTML Test
      run: |
        curl https://htmltest.wjdp.uk | bash
        bin/htmltest

   
